# Generated by Django 2.1.2 on 2020-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='社員番号')),
                ('name', models.CharField(max_length=128, verbose_name='社員名')),
                ('mail_address', models.EmailField(max_length=128, verbose_name='メールアドレス')),
            ],
        ),
    ]
